name: Deploy test
on:
  push:
    branches:
      - dev/release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          cd hieunm.vn
          git push heroku master
